default: &default
  adapter: postgresql
  encoding: unicode
  Username: john
  password: johndoee
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: info_blog_development

test:
  <<: *default
  database: info_blog_test

production:
  <<: *default
  database: info_blog_production
  username: info_blog
  password: <%= ENV['INFO_BLOG_DATABASE_PASSWORD'] %>
